#!/bin/bash
FALCO_TRACE_BIN_DIR=/falco-trace
FALCO_DIR=${FALCO_TRACE_BIN_DIR}/falco
SYSDIG_DIR=${FALCO_TRACE_BIN_DIR}/sysdig
PDIG_DIR=${FALCO_TRACE_BIN_DIR}/pdig
ETC=${FALCO_TRACE_BIN_DIR}/etc

ls -ltr $FALCO_DIR

cd $FALCO_DIR

wget --no-check-certificate https://download.falco.org/packages/bin/x86_64/falco-0.22.1-x86_64.tar.gz
tar -xzf falco-0.22.1-x86_64.tar.gz
cd falco-0.22.1-x86_64
cp -rv etc/falco /etc/falco
cp -v $ETC/falco/falco.yaml /etc/falco/falco.yaml
cp -rv usr/bin/falco /usr/bin/falco
cp -rv usr/share/falco /usr/share/falco

# ----------------------------------------------------------------------------------------------------
# [ INSTALL PDIG ]
#
cd $PDIG_DIR
rm -rf build # Wipe build for a clean install every time
mkdir build
cd build
cmake ../
make
cp pdig /usr/bin/pdig